In [1]:
# !git clone https://github.com/cybergis/CyberGIS-Vis

In [2]:
import pandas as pd
import geopandas as gpd
from Adaptive_Choropleth_Mapper import Adaptive_Choropleth_Mapper_viz, Adaptive_Choropleth_Mapper_log

In [5]:
Covid_2020 = pd.read_csv("attributes_new/Covid_Rate_daily_counties_mainland.csv", dtype={'geoid':str})
# Covid_2020 = Covid_2020.astype({'Zipcode':'string'})
# Covid_2020 = Covid_2020.rename(columns={'Zipcode': 'geoid','variable': 'period'})
Covid_2020

,geoid,period,county,state,confirmed_cases_total,death_total,cases,death,confirmed_rate_total,death_rate_tatal,confirmed_rate,death_rate,pop
0,1001,2020-04-01,Autauga,Alabama,10,0.0,3,0,1.81,0.0,0.54,0.0,55200
1,1001,2020-04-02,Autauga,Alabama,10,0.0,0,0,1.81,0.0,0.00,0.0,55200
2,1001,2020-04-03,Autauga,Alabama,12,0.0,2,0,2.17,0.0,0.36,0.0,55200
3,1001,2020-04-04,Autauga,Alabama,12,0.0,0,0,2.17,0.0,0.00,0.0,55200
4,1001,2020-04-05,Autauga,Alabama,12,0.0,0,0,2.17,0.0,0.00,0.0,55200
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1013504,72153,2021-02-15,Yauco,Puerto Rico,985,NaN,0,0,270.31,0.0,0.00,0.0,36439
1013505,72153,2021-02-16,Yauco,Puerto Rico,989,NaN,4,0,271.41,0.0,1.10,0.0,36439
1013506,72153,2021-02-17,Yauco,Puerto Rico,991,NaN,2,0,271.96,0.0,0.55,0.0,36439
1013507,72153,2021-02-18,Yauco,Puerto Rico,992,NaN,1,0,272.24,0.0,0.27,0.0,36439
1013508,72153,2021-02-19,Yauco,Puerto Rico,993,NaN,1,0,272.51,0.0,0.27,0.0,36439

In [7]:
shapefile_US = gpd.read_file("shp_new/counties.shp", dtype={'zipcode':str, 'community':str})
shapefile_US = shapefile_US.rename(columns={'zipcode': 'geoid', 'community':'name'})
shapefile_US

,geoid,name,geometry
0,2013,"Aleutians East,AK","MULTIPOLYGON (((-162.63769 54.80112, -162.6440..."
1,2016,"Aleutians West,AK","MULTIPOLYGON (((177.44593 52.11133, 177.44302 ..."
2,28107,"Panola,MS","POLYGON ((-90.19854 34.51109, -90.19863 34.554..."
3,28101,"Newton,MS","POLYGON ((-88.91452 32.57695, -88.91559 32.558..."
4,28027,"Coahoma,MS","POLYGON ((-90.65700 33.98759, -90.66036 33.987..."
...,...,...,...
3216,27057,"Hubbard,MN","POLYGON ((-95.16917 47.15252, -95.16909 47.182..."
3217,27169,"Winona,MN","POLYGON ((-92.07949 44.10699, -92.07921 44.117..."
3218,2270,None,"POLYGON ((-160.85114 63.01269, -160.85156 62.9..."
3219,51515,None,"POLYGON ((-79.54339 37.32615, -79.54230 37.334..."
3220,46113,None,"POLYGON ((-102.79211 42.99998, -102.86790 42.9..."

In [8]:
param_MLC_COVID_US_2020 = {
    'title': "Temporal Patterns of Covid-19 Crude Rate and Vaccined Rate at Zip Code Level in US Counties",
    'Subject': "Temporal Patterns",
    'filename_suffix': "COVID_MLC_US_2010",    
    'inputCSV': Covid_2020,   
    'shapefile': shapefile_US, 
    'periods': "All",
    'variables': [       
            "confirmed_rate", 
            "death_rate",
            "confirmed_rate_total",
            "death_rate_tatal"
        ],
    'NumOfMaps':2,
    'InitialLayers':["2020-08-01_confirmed_rate" , "2020-08-26_confirmed_rate"],
    'Initial_map_center':[37, -97],
    'Initial_map_zoom_level':4,    
    'Map_width':"650px",
    'Map_height':"380px", 
    'Top10_Chart': True,     
    'Multiple_Line_Chart': True,
    'NumOfMLC':4,
     'titlesOfMLC':["1. Confirmed Rate (Confirmed Cases per 10k population)", "2. Death Rate (Deaths per  10k population)", "3. Cumulative Confirmed Rate", "4. Cumulative Death Rate"],  
    'DefaultRegion_MLC':"6073" 
}
Adaptive_Choropleth_Mapper_viz(param_MLC_COVID_US_2020)

/cvmfs/cybergis.illinois.edu/software/conda/cybergisx/python3-0.9.0/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:1990: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  result[:] = values

output directory :  ACM_COVID_MLC_US_2010
To see your visualization, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/shariprasad/view/CyberGIS_new/ACM_COVID_MLC_US_2010/index.html
To access all visualizations that you have created, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/shariprasad/view/CyberGIS_new//ACM_log.html
Advanced options are available in
https://cybergisx.cigi.illinois.edu/user/shariprasad/edit/CyberGIS_new/ACM_COVID_MLC_US_2010/data/CONFIG_COVID_MLC_US_2010.js

In [9]:
param_CLC_COVID3 = {
    'title': "Comparison of Temporal Patterns of Covid-19 Crude Rate between US Counties",
    'Subject': "Temporal Patterns",
    'filename_suffix': "COVID_CLC_US_2020",                                    
    'inputCSV': Covid_2020,   
    'shapefile': shapefile_US, 
    'periods': "All",
    'variables': [        
            "confirmed_rate", 
        ],
    'NumOfMaps':2,
    'InitialLayers':["2020-04-01_confirmed_rate" , "2020-08-26_confirmed_rate"],
    'Initial_map_center':[37, -97],
    'Initial_map_zoom_level':4,    
    'Map_width':"650px",
    'Map_height':"450px",      
    'Top10_Chart': True,     
    'Comparision_Chart': True,
    #'NumOfCLC': 46,
    'DefaultRegion_CLC': ["06037", "12086"] 
}
Adaptive_Choropleth_Mapper_viz(param_CLC_COVID3)

output directory :  ACM_COVID_CLC_US_2020
To see your visualization, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/shariprasad/view/CyberGIS_new/ACM_COVID_CLC_US_2020/index.html
To access all visualizations that you have created, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/shariprasad/view/CyberGIS_new//ACM_log.html
Advanced options are available in
https://cybergisx.cigi.illinois.edu/user/shariprasad/edit/CyberGIS_new/ACM_COVID_CLC_US_2020/data/CONFIG_COVID_CLC_US_2020.js